backend:
  name: git-gateway
  branch: main # Branch to update (e.g., main or master)

media_folder: "static/images/uploads" # Where images will be stored in the repo
public_folder: "/images/uploads" # Where the images will be accessible

collections:
  - label: "Posts"
    name: "posts" # Used in the URL of the CMS, e.g., /admin/collections/blog
    label_singular: "Post"
    folder: "content/posts" # Folder for blog posts
    create: true
    #slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }
      - { label: "Categoría", name: "categories", widget: "list", default: ["noticias"] }
      - { label: "Etiquetas", name: "tags", widget: "list", default: ["san javier"] }
      - { label: "Imagen presentación", name: "image", widget: "image"}
      - { label: "Imagen presentación ALT", name: "featureimage", widget: "image", media_folder: "static/images/uploads", public_folder: "/images/uploads" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
